spring:
  application:
    name: smart-campus

  datasource:
    url: ${NEON_DB_URL}
    username: ${NEON_DB_USER}
    password: ${NEON_DB_PASS}

  sql:
    init:
      mode: never

server:
  port: 8080
